# Bus单机部署, 使用http
include:
  - ../docker/mysql8/compose.yml
  - ../docker/rabbitmq/compose.yml
  - ../docker/redis/compose.yml
  - ../docker/bus/compose.yml
  - path:  
    - ../docker/video-nginx/compose.yml
    - ../docker/video-nginx/compose.http.yml
  - path:  
    - ../docker/video/compose.yml
    - ../docker/video/compose.bus.yml
    - ../docker/video/compose.bus.http.yml
  - path:
    - ../docker/nginx/compose.yml
    - ../docker/nginx/compose.bus.yml
    - ../docker/nginx/compose.bus.http.yml
  - path:
    - ../docker/web-downloader/compose.yml
    - ../docker/web-downloader/compose.bus.yml
