## V2 single machine deployment solution
# 1. Modify .env file. Initialize various passwords
# 2. docker compose up -d to start service
include:
  - ../docker/mysql8/compose.yml
  - ../docker/mysql-backup/compose.maintain.yml
  - ../docker/redis/compose.yml
  - ../docker/mongodb/compose.yml
  - ../docker/rabbitmq/compose.yml
  - ../docker/minio/compose.yml
  - ../docker/maintain/compose.yml
  - ../docker/jtt808/compose.yml
  - ../docker/video/compose.yml
  - path:
    - ../docker/nginx/compose.yml
    - ../docker/nginx/compose.track.yml
    - ../docker/nginx/compose.video.yml
  - path:
    - ../docker/web-downloader/compose.yml
    - ../docker/web-downloader/compose.track.yml
