## Video service example
# Just include all required compose files
# Recommend customers open consecutive port range 9000-9100
# Default open ports: live 9000, recording 9001, intercom 9002, monitoring 9003, broadcast 9004, RTMP 9005:1935 (srs)
# Nginx proxy 9085-9089: http-flv (srs:8080 port), wss (rtp:9006 port), intercept mdvr and ws keywords
include:
  - path:
    - ../docker/nginx/compose.yml
    - ../docker/nginx/compose.video.yml
  - path:
    - ../docker/video/compose.yml
