## V2 standalone deployment scheme, using http
include:
  - ../docker/mysql8/compose.yml
  - ../docker/mysql-backup/compose.maintain.yml
  - ../docker/redis/compose.yml
  - ../docker/mongodb/compose.yml
  - ../docker/rabbitmq/compose.yml
  - ../docker/minio/compose.yml
  - ../docker/maintain/compose.yml
  - ../docker/jtt808/compose.yml
  - path:
    - ../docker/video/compose.yml
    - ../docker/video/compose.storage.yml
    - ../docker/video/compose.http.yml
  - path:
    - ../docker/nginx/compose.yml
    - ../docker/nginx/compose.track.yml
    - ../docker/nginx/compose.video.yml
    - ../docker/nginx/compose.video.http.yml
  - path:
    - ../docker/web-downloader/compose.yml
    - ../docker/web-downloader/compose.track.yml